apiVersion: v1
kind: Service
metadata: 
  name: db
  labels:
    name: db_service
    app: voting_app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgress_pod
    app: voting_app