apiVersion: v1
kind: Pod
metadata: 
  name: postgress-pod
  labels:
    name: postgress-pod
    app: voting-app
spec:
  containers:
    - name: postgress
      image: postgres:9.4
      ports:
      - containerPort: 5432
