apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    name: redis_service
    app: voting_app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis_pod
    app: voting_app