apiVersion: v1
kind: Pod
metadata: 
  name: redis_pod
  labels:
    name: redis_pod
    app: voting_app
spec:
  containers:
    - name: redis
      image: redis
      ports:
      - containerPort: 6379