apiVersion: v1
kind: Pod
metadata: 
  name: result_app_pod
  labels:
    name: result_app_pod
    app: voting_app
spec:
  containers:
    - name: result_app
      image: dockersamples/examplevotingapp_result
      ports:
      - containerPort: 80